### PR TITLE
[MicroByte] Memory Leak

### LINKED ISSUE #2: Add Activities to MicroByte on Memory Leak
**MicroByte Title:** Memory Leak

**Improvement Proposal:** 

- Addition of Programs written in C to demonstrate memory leaks
- Addition of Engaging Activities involving debugging, looking at logs

**Benefits of proposed improvements:** 

Learners will be able to grasp the concepts better when they perform simple activities rather than reading through a tutorial.

### PR DESCRIPTION
**Pull request by sudiptog81**
### Checklist: 

- [x] Added/updated activities for learners
- [x] Didn't give the solutions to the added/updated activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by YourAKShaw — APPROVED** [review]
@sudiptog81 This is **almost like you've created a full fledged Crio Byte**. High chances that your work might be published on the [Crio.Do](https://www.crio.do/) website. Keep rocking! :rocket: 

_P.S.: I really like the way you present the minor details, coz that's what makes a content, quality content._

**Review by Kevinpaulose05 — APPROVED** [review]
Needless to say awesome work. Totally agree with @Ak-Shaw 's comment. Nicely managed the timeframe from issue opeing to PR submission. Keep up the work and keep contributing. 

We would appreciate a quick favor from u. For both the microbytes you have submitted can u kindly open up some issues for learners (just brief simple issues should do), if there exists any scope for them.

**Comment by sudiptog81** [comment]
@Kevinpaulose05 I have gone ahead and opened up a couple of issues.

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @sudiptog81 for:

- code
- content
- ideas
- doc

**Comment by YourAKShaw** [comment]
@sudiptog81 Kindly showcase your new MicroByte using [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md) template.

**Pull request merged**
