### PR TITLE
renamed the folder ! 

### PR DESCRIPTION
**Pull request by sudhanshutiwari264**
Os virtual memory folder which is not able to be cloned on windows due to "|".

### CODE REVIEW

**Comment by sudiptog81** [comment]
I suggest the folder to be renamed as **Virtual Memory (Memory Leak)** as the naming **Virtual memory ( Memory leak)** has an extra space after the opening parentheses.

**Comment by Kevinpaulose05** [comment]
@sudiptog81 Refer [this](https://brendanforster.com/notes/fixing-invalid-git-paths-on-windows/) for that issue. We have renamed the file so go right ahead.
Cheers

**Comment by sudhanshutiwari264** [comment]
@sudiptog81 thanks for pointing the error I totally forgot it!

**Comment by sudiptog81** [comment]
@Kevinpaulose05 thanks for the resource, I'll update my fork.

**Pull request merged**
